### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by Alex293** [BatchLabs/Batch-iOS-mixpanel-swift-dispatcher#2]
Hi, is this project still maintained ? The dependencies are outdated and are blocking updating our dependencies. 

Can you update bump the dependencies or should I fork ?

**Comment by abarisain** [comment]
Hi,
Thanks for bringing this to our attention

I tracked an internal issue to update the dependencies, but I'm not sure we will be able to work on this until mid-september. If you need to update in the meantime, feel free to fork.

**Comment by Alex293** [comment]
Just made a PR https://github.com/BatchLabs/Batch-iOS-mixpanel-swift-dispatcher/pull/3 for this. Changes seem compatible but I can't run the tests. I'll try using the fork in my app and report back if there is any issue.

**Comment by abarisain** [comment]
Thanks

As the tests mock out mixpanel, I don't think they're gonna break. I'll have the CI run them.

**Comment by abarisain** [comment]
3.0.0 should do it, thanks for the PR
